from setuptools import setup
setup(name='djangobp',
      version='1.0',
      packages=['djangobp', 
                'djangobp.management', 
                'djangobp.management.commands', 
                'djangobp.scaffold',
                'djangobp.scaffold.app',
                'djangobp.scaffold.app.controllers',
                'djangobp.scaffold.app.static',
                'djangobp.scaffold.app.templates',
                'djangobp.scaffold.modelscaffold',
                'djangobp.scaffold.modelscaffold.templates',
                'djangobp.scaffold.modelscaffold.common',
                ],
      package_data={'djangobp.scaffold.app.static': ['css/*', 'js/*', 'images/*', 'fancybox/*'],
                    'djangobp.scaffold.app.templates': ['*'],
                    'djangobp.scaffold.modelscaffold.templates': ['*'],
                    'djangobp.scaffold.modelscaffold.common': ['*'],
                    },
      scripts=['scripts/djangobp-install.py']
      )
